# Generated by Django 4.0.4 on 2022-11-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['first_name'], 'verbose_name': 'actor', 'verbose_name_plural': 'actors'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['first_name'], 'verbose_name': 'director', 'verbose_name_plural': 'directors'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
    ]
